using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;

namespace SonadaBeds.Web.Models;
public class ApplicationUser : IdentityUser { public string? FullName { get; set; } }
public class Category { public int Id { get; set; } [Required] public string Name { get; set; } = ""; [Required] public string Slug { get; set; } = ""; public string? Description { get; set; } public ICollection<Product> Products { get; set; } = []; }
public class Product { public int Id { get; set; } [Required] public string Name { get; set; } = ""; [Required] public string Slug { get; set; } = ""; public string? Description { get; set; } public decimal BasePrice { get; set; } public string ImageUrl { get; set; } = ""; public bool Featured { get; set; } public int CategoryId { get; set; } public Category? Category { get; set; } public ICollection<ProductOption> Options { get; set; } = []; public ICollection<ProductReview> Reviews { get; set; } = []; }
public class ProductOption { public int Id { get; set; } public int ProductId { get; set; } public string GroupName { get; set; } = ""; public string Name { get; set; } = ""; public decimal PriceAdjustment { get; set; } public string? Swatch { get; set; } public Product? Product { get; set; } }
public class CartItem { public int Id { get; set; } public int ProductId { get; set; } public string ProductName { get; set; } = ""; public decimal UnitPrice { get; set; } public int Quantity { get; set; } public string ConfigurationJson { get; set; } = "{}"; }
public class Order { public int Id { get; set; } public string OrderNumber { get; set; } = ""; public string? UserId { get; set; } public DateTime CreatedUtc { get; set; } = DateTime.UtcNow; public string Status { get; set; } = "Pending"; public decimal Subtotal { get; set; } public decimal Delivery { get; set; } public decimal Discount { get; set; } public decimal Total { get; set; } public string Email { get; set; } = ""; public string ShippingAddress { get; set; } = ""; public ICollection<OrderItem> Items { get; set; } = []; }
public class OrderItem { public int Id { get; set; } public int OrderId { get; set; } public string ProductName { get; set; } = ""; public decimal UnitPrice { get; set; } public int Quantity { get; set; } public string ConfigurationJson { get; set; } = "{}"; public Order? Order { get; set; } }
public class ProductReview { public int Id { get; set; } public int ProductId { get; set; } public string CustomerName { get; set; } = ""; public int Rating { get; set; } public string Comment { get; set; } = ""; public bool Approved { get; set; } public DateTime CreatedUtc { get; set; } = DateTime.UtcNow; }
public class Coupon { public int Id { get; set; } public string Code { get; set; } = ""; public decimal PercentOff { get; set; } public decimal? MinimumSpend { get; set; } public DateTime? ExpiresUtc { get; set; } public bool Active { get; set; } = true; }
public class NewsletterSubscriber { public int Id { get; set; } public string Email { get; set; } = ""; public DateTime CreatedUtc { get; set; } = DateTime.UtcNow; }
public class SwatchRequest { public int Id { get; set; } public string Name { get; set; } = ""; public string Email { get; set; } = ""; public string Address { get; set; } = ""; public string Fabrics { get; set; } = ""; public DateTime CreatedUtc { get; set; } = DateTime.UtcNow; }
public class PostcodeRule { public int Id { get; set; } public string Prefix { get; set; } = ""; public decimal DeliveryFee { get; set; } public int EstimatedDays { get; set; } }
public class CmsPage { public int Id { get; set; } public string Slug { get; set; } = ""; public string Title { get; set; } = ""; public string Content { get; set; } = ""; }
public class Faq { public int Id { get; set; } public string Question { get; set; } = ""; public string Answer { get; set; } = ""; public int SortOrder { get; set; } }
